#!/bin/sh

set -e

./genconf

for s in linux-headers cross-binutils cross-gcc-static musl \
	cross-gcc filesystem zlib binutils m4 libgmp libmpfr \
	libmpc gcc make file busybox libressl rsync curl pkg; do
	cd scripts
	echo "Running script $s.sh"
	./$s.sh
	cd - >/dev/null
done

echo "Copying scripts and files..."
./cpscripts

exit 0
