#!/bin/sh

CARCH=x86_64
TARGET=$CARCH-linux-musl
ROOTFS=$TARGET-rootfs
CROOTFS=alicelinux-$CARCH.tar.xz

[ -d $ROOTFS ] || {
	echo "rootfs not found"
	exit 1
}

rm -f $CROOTFS
cd $ROOTFS
tar --exclude=var/lib/pkg/sources/* \
	--exclude=var/lib/pkg/work/* \
	-cvJpf ../$CROOTFS *
cd - >/dev/null

exit 0
