#!/bin/sh

as_root()
{
	if [ $(id -u) = 0 ]; then
		$*
	elif [ -x /usr/bin/sudo ]; then
		sudo $*
	else
		su -c \\"$*\\"
	fi
}

if [ -f ./xpkg.conf ]; then
	. ./xpkg.conf
else
	echo "error: please run ./genconf first"
	exit 1
fi

as_root chown -Rv 0:0 $ROOT_DIR

exit $?
