#!/bin/sh

pkgname=${0##*/}
pkgname=${pkgname%.sh}

SRCDIR="$(realpath ../sources)"
FILEDIR="$(realpath ../files)"
WORKDIR="$(realpath ../src_$pkgname)"
PKG="$(realpath ../pkg_$pkgname)"
ROOT=${ROOT:-/}
DB="$ROOT/var/lib/pkg"
CONF=${CONF:-./conf}

[ -f "$CONF" ] && . "$CONF"

mkdir -p $SRCDIR
rm -fr $WORKDIR $PKG
mkdir -p $WORKDIR $PKG

fetch() {
	[ "$1" ] || exit 1
	if [ ! -f $SRCDIR/${1##*/} ]; then
		echo ":: fetching $1"
		curl -Lfo $SRCDIR/${1##*/} $1 || exit 1
	fi
}

unpack() {
	[ "$1" ] || exit 1
	echo ":: unpacking $SRCDIR/${1##*/}"
	tar xf $SRCDIR/${1##*/} -C $WORKDIR || exit 1
}

fetchunpack() {
	fetch $1
	unpack $1
}

pkginstall() {
	mkdir -p $DB
	v=${1:-0}
	# remove libtool files
	find $PKG ! -type d -name "*.la" -delete
	echo ":: installing package $pkgname-$v to $ROOT"
	cp -rp $PKG/* $ROOT
	echo $v > $DB/$pkgname
	find $PKG -printf "%P\n" 2>/dev/null | sed '/^$/d' >> $DB/$pkgname
	rm -fr $WORKDIR $PKG
	echo ":: package $pkgname-$v installed"
}
