#!/bin/sh -e

SCRIPT_DIR="/var/lib/pkg/scripts"
FILES_DIR="/var/lib/pkg/files"

cd /tmp
rm -f alicelinux-main.zip
echo "Fetching AliceLinux scripts..."
curl -# -LJO https://github.com/emmett1/alicelinux/archive/main.zip
unzip -q alicelinux-main.zip
echo "Sync updated scripts..."
rsync -a alicelinux-main/scripts/ $SCRIPT_DIR
rsync -a alicelinux-main/files/ $FILES_DIR
rm -fr alicelinux-main
echo "Scripts updated."

exit 0
